name: Local MERN CI/CD

on:
  push:
    branches:
      - dev-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to local Ubuntu server
        run: |
          # Add the SSH private key to the SSH agent
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.LOCAL_IP }}" >> ~/.ssh/known_hosts
          ssh "${{ secrets.USERNAME }}@${{ secrets.LOCAL_IP }}"

      - name: Run on ubuntu server
        run: npm run start-prod
